use_frameworks!

platform :ios, '10.0'

target 'GDMonitor_Example' do
  pod 'GDMonitor', :path => '../'
  pod 'DoraemonKit/Core', :path => '../../../Github/DoKit/'
  pod 'FLEX', :path => '../../../Github/FLEX/'
  pod 'LookinServer', :path => '../../../Github/LookinServer/'
  
  target 'GDMonitor_Tests' do
    inherit! :search_paths

    
  end
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
#    end
#  end
#end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
       end
    end
  end
end
