//
//  GDMonitorVMRegionModel.h
//  GDMonitor
//
//  Created by beilu on 2021/12/7.
//

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSUInteger, VM_MEMORY_REGOIN) {
    MEMORY_MALLOC = 1,
    MEMORY_MALLOC_SMALL = 2,
    MEMORY_MALLOC_LARGE = 3,
    MEMORY_MALLOC_HUGE = 4,
    MEMORY_SBRK = 5,
    MEMORY_REALLOC = 6,
    MEMORY_MALLOC_TINY = 7,
    MEMORY_MALLOC_LARGE_REUSABLE = 8,
    MEMORY_MALLOC_LARGE_REUSED = 9,
    MEMORY_ANALYSIS_TOOL = 10,
    MEMORY_MALLOC_NANO = 11,
    MEMORY_MALLOC_MEDIUM = 12,
    MEMORY_MALLOC_PGUARD = 13,
    MEMORY_MALLOC_PROB_GUARD = 13,
    MEMORY_MACH_MSG = 20,
    MEMORY_IOKIT = 21,
    MEMORY_STACK = 30,
    MEMORY_GUARD = 31,
    MEMORY_SHARED_PMAP = 32,
    MEMORY_DYLIB = 33,
    MEMORY_OBJC_DISPATCHERS = 34,
    MEMORY_UNSHARED_PMAP = 35,
    MEMORY_APPKIT = 40,
    MEMORY_FOUNDATION = 41,
    MEMORY_COREGRAPHICS = 42,
    MEMORY_CORESERVICES = 43,
    MEMORY_CARBON = MEMORY_CORESERVICES,
    MEMORY_JAVA = 44,
    MEMORY_COREDATA = 45,
    MEMORY_COREDATA_OBJECTIDS = 46,
    MEMORY_ATS = 50,
    MEMORY_LAYERKIT = 51,
    MEMORY_CGIMAGE = 52,
    MEMORY_TCMALLOC = 53,
    MEMORY_COREGRAPHICS_DATA = 54,
    MEMORY_COREGRAPHICS_SHARED = 55,
    MEMORY_COREGRAPHICS_FRAMEBUFFERS = 56,
    MEMORY_COREGRAPHICS_BACKINGSTORES = 57,
    MEMORY_COREGRAPHICS_XALLOC = 58,
    MEMORY_COREGRAPHICS_MISC = MEMORY_COREGRAPHICS,
    MEMORY_DYLD = 60,
    MEMORY_DYLD_MALLOC = 61,
    MEMORY_SQLITE = 62,
    MEMORY_JAVASCRIPT_CORE = 63,
    MEMORY_WEBASSEMBLY = MEMORY_JAVASCRIPT_CORE,
    MEMORY_JAVASCRIPT_JIT_EXECUTABLE_ALLOCATOR = 64,
    MEMORY_JAVASCRIPT_JIT_REGISTER_FILE = 65,
    MEMORY_GLSL = 66,
    MEMORY_OPENCL = 67,
    MEMORY_COREIMAGE = 68,
    MEMORY_WEBCORE_PURGEABLE_BUFFERS = 69,
    MEMORY_IMAGEIO = 70,
    MEMORY_COREPROFILE = 71,
    MEMORY_ASSETSD = 72,
    MEMORY_OS_ALLOC_ONCE = 73,
    MEMORY_LIBDISPATCH = 74,
    MEMORY_ACCELERATE = 75,
    MEMORY_COREUI = 76,
    MEMORY_COREUIFILE = 77,
    MEMORY_GENEALOGY = 78,
    MEMORY_RAWCAMERA = 79,
    MEMORY_CORPSEINFO = 80,
    MEMORY_ASL = 81,
    MEMORY_SWIFT_RUNTIME = 82,
    MEMORY_SWIFT_METADATA = 83,
    MEMORY_DHMM = 84,
    MEMORY_SCENEKIT = 86,
    MEMORY_SKYWALK = 87,
    MEMORY_IOSURFACE = 88,
    MEMORY_LIBNETWORK = 89,
    MEMORY_AUDIO = 90,
    MEMORY_VIDEOBITSTREAM = 91,
    MEMORY_CM_XPC = 92,
    MEMORY_CM_RPC = 93,
    MEMORY_CM_MEMORYPOOL = 94,
    MEMORY_CM_READCACHE = 95,
    MEMORY_CM_CRABS = 96,
    MEMORY_QUICKLOOK_THUMBNAILS = 97,
    MEMORY_ACCOUNTS = 98,
    MEMORY_SANITIZER = 99,
    MEMORY_IOACCELERATOR = 100,
    MEMORY_CM_REGWARP = 101,
    MEMORY_EAR_DECODER = 102,
    MEMORY_COREUI_CACHED_IMAGE_DATA = 103,
    MEMORY_COLORSYNC = 104,
    MEMORY_ROSETTA = 230,
    MEMORY_ROSETTA_THREAD_CONTEXT = 231,
    MEMORY_ROSETTA_INDIRECT_BRANCH_MAP = 232,
    MEMORY_ROSETTA_RETURN_STACK = 233,
    MEMORY_ROSETTA_EXECUTABLE_HEAP = 234,
    MEMORY_ROSETTA_USER_LDT = 235,
    MEMORY_ROSETTA_ARENA = 236,
    MEMORY_ROSETTA_10 = 239,
    MEMORY_APPLICATION_SPECIFIC_1 = 240,
    MEMORY_APPLICATION_SPECIFIC_16 = 255,
};

NS_ASSUME_NONNULL_BEGIN

@interface GDMonitorVMRegionModel : NSObject

@property (nonatomic, assign) VM_MEMORY_REGOIN regoin;
@property (nonatomic, assign) vm_address_t address;
@property (nonatomic, assign) vm_size_t size;

@end

@interface GDMonitorVMBlockModel : NSObject

@property (nonatomic, copy) NSString *name;
@property (nonatomic, strong) NSMutableArray<GDMonitorVMRegionModel *> *vmRegions;

@end

NS_ASSUME_NONNULL_END
